-- Finanças - Supabase Schema
CREATE TABLE IF NOT EXISTS contas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('corrente', 'investimento', 'especie', 'cartao')),
  saldo_inicial NUMERIC(12, 2) NOT NULL DEFAULT 0,
  cor TEXT NOT NULL DEFAULT '#12805d',
  ordem INTEGER NOT NULL DEFAULT 0,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_contas_user_id ON contas(user_id);

CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa')),
  cor TEXT NOT NULL DEFAULT '#b28a4b',
  ordem INTEGER NOT NULL DEFAULT 0,
  criado_em TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, nome, tipo)
);
CREATE INDEX IF NOT EXISTS idx_categorias_user_id ON categorias(user_id);

CREATE TABLE IF NOT EXISTS lancamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  conta_id BIGINT NOT NULL REFERENCES contas(id) ON DELETE CASCADE,
  conta_destino_id BIGINT REFERENCES contas(id) ON DELETE CASCADE,
  tipo TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa', 'transferencia')),
  categoria_id BIGINT REFERENCES categorias(id) ON DELETE SET NULL,
  valor NUMERIC(12, 2) NOT NULL CHECK (valor > 0),
  data DATE NOT NULL,
  descricao TEXT NOT NULL DEFAULT '',
  criado_em TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_lancamentos_user_id ON lancamentos(user_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_conta_id ON lancamentos(conta_id);
CREATE INDEX IF NOT EXISTS idx_lancamentos_data ON lancamentos(data DESC);

CREATE TABLE IF NOT EXISTS recorrentes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK (tipo IN ('receita', 'despesa')),
  conta_id BIGINT NOT NULL REFERENCES contas(id) ON DELETE CASCADE,
  categoria_id BIGINT REFERENCES categorias(id) ON DELETE SET NULL,
  valor NUMERIC(12, 2) NOT NULL CHECK (valor > 0),
  frequencia TEXT NOT NULL CHECK (frequencia IN ('mensal', 'semanal')),
  dia INTEGER NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  ultimo_processado DATE,
  criado_em TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_recorrentes_user_id ON recorrentes(user_id);

CREATE TABLE IF NOT EXISTS limites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  categoria_id BIGINT NOT NULL REFERENCES categorias(id) ON DELETE CASCADE,
  valor_mensal NUMERIC(12, 2) NOT NULL CHECK (valor_mensal > 0),
  UNIQUE (user_id, categoria_id)
);
CREATE INDEX IF NOT EXISTS idx_limites_user_id ON limites(user_id);

CREATE TABLE IF NOT EXISTS metas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  valor_alvo NUMERIC(12, 2) NOT NULL CHECK (valor_alvo > 0),
  conta_id BIGINT NOT NULL REFERENCES contas(id) ON DELETE CASCADE,
  data_alvo DATE,
  cor TEXT NOT NULL DEFAULT '#12805d',
  criado_em TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_metas_user_id ON metas(user_id);

-- RLS
ALTER TABLE contas ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE lancamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE recorrentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE limites ENABLE ROW LEVEL SECURITY;
ALTER TABLE metas ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['contas', 'categorias', 'lancamentos', 'recorrentes', 'limites', 'metas']
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I_select ON %I', t, t);
    EXECUTE format('DROP POLICY IF EXISTS %I_insert ON %I', t, t);
    EXECUTE format('DROP POLICY IF EXISTS %I_update ON %I', t, t);
    EXECUTE format('DROP POLICY IF EXISTS %I_delete ON %I', t, t);
    EXECUTE format('CREATE POLICY %I_select ON %I FOR SELECT USING (auth.uid() = user_id)', t, t);
    EXECUTE format('CREATE POLICY %I_insert ON %I FOR INSERT WITH CHECK (auth.uid() = user_id)', t, t);
    EXECUTE format('CREATE POLICY %I_update ON %I FOR UPDATE USING (auth.uid() = user_id)', t, t);
    EXECUTE format('CREATE POLICY %I_delete ON %I FOR DELETE USING (auth.uid() = user_id)', t, t);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO authenticated', t);
    EXECUTE format('GRANT USAGE ON SEQUENCE %I_id_seq TO authenticated', t);
  END LOOP;
END $$;
